alpha: 1.0
beam_size: 5
cross_coverage: true
d_model: 256
dc: 32
dim_feedforward: 1024
dropout: 0.3
early_stopping: false
growth_rate: 24
learning_rate: 0.0005
max_len: 400
milestones:
- 60
- 140
nhead: 8
num_decoder_layers: 3
num_layers: 16
optimizer_name: adamw
patience: 20
scheduler_name: warmup_plateau
self_coverage: true
temperature: 1.0
warmup_epochs: 200
warmup_steps: 5
